name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: qbr-test

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
            
      - name: workspace
        run: echo "${{ GITHUB_WORKSPACE }}"
